/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-03-24 18:54:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class alterarFull_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1553431596339L));
    _jspx_dependants.put("jar:file:/C:/Users/Vitor/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

if(session.getAttribute("usuario")!=null && session.getAttribute("admin").equals("s")){
      out.write("\r\n");
      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"IMG\\icone.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".div1{\r\n");
      out.write("\tpadding: 1%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Consultar Consolidado</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"Controle?cmd=img\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<div class=\"div1\">\r\n");
      out.write("\t\t\t<table border=\"1\" class=\"table-sm table-striped table-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\"\tsrc='IMG/fotos/p - ");
      out.print(request.getParameter("email"));
      out.write(".jpg' width=\"115px\" height=\"204px\" />\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>ID:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("id"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Nome:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("nome"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Idade:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("idade"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Nascimento:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("aniversario"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Tribo:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("tribo"));
      out.write("<br />\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Batizado:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("batizado"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("email"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"hidden\" name=\"email\" value=\"");
      out.print(request.getParameter("email"));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Telefone:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("telefone"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Retiro:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("retiro"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Quando Retiro</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("quandoretiro"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Quanto tempo<br />Consolidando:\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("quantotempoconsolidacao"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Servos:</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(request.getParameter("servos"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Foto:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"file\" id=\"file\" name=\"imagem\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"consultar.jsp\"\tclass=\"badge badge-info\">Voltar</a></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\t\r\n");
      out.write("<!-- \t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">ID:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"id\" value=\"");
      out.print(request.getParameter("id"));
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Nome:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"nome\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Digite seu Nome Completo\" maxlength=\"50\" size=\"50\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\" value=\"");
      out.print(request.getParameter("nome"));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Idade:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" name=\"idade\" size=\"50\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"ex.: 35\" required=\"required\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("idade"));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Nascimento:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"aniversario\" size=\"50\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"ex.: 01/01/2000\" maxlength=\"10\" required=\"required\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("aniversario"));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Tribo:</th>\r\n");
      out.write("\t\t\t\t<td><select name=\"tribo\">\r\n");
      out.write("\t\t\t\t\t\t<option name=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Não é da Rede\">Não Sou da Rede</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Não Tem\">Não Tenho</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Aser\">Aser</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Benjamin\">Benjamin</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Benjamin 2\">Benjamin 2</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Dã\">Dã</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Efraim\">Efraim</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Gade\">Gade</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Gideão\">Gideão</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Issacar\">Issacar</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"José\">José</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Judá\">Judá</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Levi\">Levi</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Manassés\">Manassés</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Naftali\">Naftali</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Rúben\">Rúben</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Simeão\">Simeão</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Zebulon\">Zebulon</option>\r\n");
      out.write("\t\t\t\t\t\t<option name=\"Zebulon 2\">Zebulon 2</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("tribo"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Batizado?</th>\r\n");
      out.write("\t\t\t\t<td><select name=\"batizado\">\r\n");
      out.write("\t\t\t\t\t\t<option name=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"SIM\">Sim</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"NÃO\">Não</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("batizado"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Email:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"email\" name=\"email\" size=\"50\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"ex.: consolidar@apascentar.com.br\" required=\"required\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("email"));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Telefone:</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"telefone\" size=\"50\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"ex.: 21 98765432\" maxlength=\"12\" required=\"required\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("telefone"));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Já foi ao Retiro?</th>\r\n");
      out.write("\t\t\t\t<td><select name=\"retiro\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"SIM\">Sim</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"NÃO\">Não</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("retiro"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Quando foi ao Retiro?</th>\r\n");
      out.write("\t\t\t\t<td><select name=\"quandoretiro\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Não foi\">Não Fui</option>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("quandoretiro"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Quando entrou na <br/>Consolidação?\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td><select name=\"quantotempoconsolidacao\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("quantotempoconsolidacao"));
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th bgcolor=\"#F5F5DC\" align=\"left\">Qual escola de <br/>Servos?\r\n");
      out.write("\t\t\t\t\t\tFaz? </th>\r\n");
      out.write("\t\t\t\t<td><select name=\"servos\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"NÃO FEZ\">Não Fiz</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Servos 2\">Servos 2</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Servos 3\">Servos 3</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Servos 4\">Servos 4</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Servos 5\">Servos 5</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.print(request.getParameter("servos"));
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Atualizar\" />\r\n");
      out.write("\t\t<br /> \r\n");
      out.write("\t\t -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
} else{
	response.sendRedirect("login.jsp");
}


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /alterarFull.jsp(193,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(1990);
    // /alterarFull.jsp(193,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(2017);
    // /alterarFull.jsp(193,6) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setStep(1);
    // /alterarFull.jsp(193,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("i");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /alterarFull.jsp(205,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(1990);
    // /alterarFull.jsp(205,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(2017);
    // /alterarFull.jsp(205,6) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setStep(1);
    // /alterarFull.jsp(205,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("i");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
