/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-03-24 18:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1553431596339L));
    _jspx_dependants.put("jar:file:/C:/Users/Vitor/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
if(session.getAttribute("usuario")!=null){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".topo{\r\n");
      out.write("\tbackground: #EEEED1;\r\n");
      out.write("}\r\n");
      out.write(".div1{\r\n");
      out.write("\tpadding: 1%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"IMG\\icone.ico\" type=\"image/x-icon\" />\r\n");
      out.write(" \r\n");
      out.write(" <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<!--  jquery UI -->\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.12.1/jquery-ui.min.js\" > </script>\r\n");
      out.write("\t\r\n");
      out.write("<link href=\"js/jquery-ui-1.12.1/jquery-ui.min.css\" rel=\"stylesheet\" />\t\r\n");
      out.write("\t<!--  JS code -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("         $(function() {\r\n");
      out.write("        \t $.datepicker.setDefaults(\r\n");
      out.write("  \t\t\t  $.extend(\r\n");
      out.write("  \t\t\t    {\"dateFormat\":\"dd/mm/yy\"},\r\n");
      out.write("  \t\t\t    $.datepicker.regional[\"pt\"]\r\n");
      out.write("  \t\t\t  )\r\n");
      out.write("  \t\t\t);        \t \r\n");
      out.write("            $( \"#nascimento\" ).datepicker({\r\n");
      out.write("            \tchangeMonth: true,\r\n");
      out.write("                changeYear: true,\r\n");
      out.write("                yearRange: '1900:',\r\n");
      out.write("                dayNamesMin: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],\r\n");
      out.write("                monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],\r\n");
      out.write("                monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("           // $( \"#nascimento\" ).datepicker(\"show\");\r\n");
      out.write("            \r\n");
      out.write("            $(\"#form\").submit(function(obj){\r\n");
      out.write("            \t\r\n");
      out.write("            \treturn true\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("         });\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("<title>Cadastro da Consolidação</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
if(session.getAttribute("msg")!=null){
      out.write('\r');
      out.write('\n');
}else{
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"topo\">\r\n");
      out.write("\t<marquee>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</marquee>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"div1\">\r\n");
      out.write("<h2>Consolidação - Cadastro</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("Olá <font color=\"red\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></font>, seja bem-vindo(a).\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t");
 String admin = "s";
		if(session.getAttribute("admin")!=admin){ 
      out.write("\r\n");
      out.write("\t\t\t<td><form action=\"Controle?cmd=logout\" method=\"post\"><button type=\"submit\" class=\"btn btn-danger btn-sm\" title=\"Sair do Sistema\">logoff</button></form></td>\r\n");
      out.write("\t\t\t<td><form action=\"Controle?cmd=cadastraralmas\" method=\"post\"><button type=\"submit\" class=\"btn btn-warning btn-sm\" title=\"Cadastrar Consolidados\">cadastrar almas</button></form></td>\r\n");
      out.write("\t\t");
}if(session.getAttribute("admin").equals(admin)){ 
      out.write("\r\n");
      out.write("\t\t\t<td><form action=\"Controle?cmd=consultarconsolidadores\" method=\"post\"><button type=\"submit\" class=\"btn btn-warning btn-sm\" title=\"Consultar Lista de Consolidadores\">consolidadores</button></form></td>\r\n");
      out.write("\t\t\t<td><form action=\"Controle?cmd=acessoadmin\" method=\"post\"><button type=\"submit\" class=\"btn btn-warning btn-sm\" title=\"Conceder acesso de Administrador\">admin</button></form></td>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h3>Informe seus dados:</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"Controle?cmd=gravar\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table border=\"0\" bgcolor=\"#E8E8E8\" class=\"table table-sm table-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\"><label for=\"exampleInputEmail1\">Nome</label></th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" name=\"nome\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Digite seu Nome Completo\" maxlength=\"50\" required=\"required\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Idade:</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" name=\"idade\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"ex.: 35\" required=\"required\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Nascimento:</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"nascimento\" aria-describedby=\"emailHelp\" name=\"aniversario\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"ex.: 01/01/2000\" maxlength=\"10\" required=\"required\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Tribo:</th>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"tribo\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Não é da Rede\">Não Sou da Rede</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Não Tem\">Não Tenho</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Aser\">Aser</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Benjamin\">Benjamin</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Benjamin 2\">Benjamin 2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Dã\">Dã</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Efraim\">Efraim</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Gade\">Gade</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Gideão\">Gideão</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Issacar\">Issacar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"José\">José</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Judá\">Judá</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Levi\">Levi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Manassés\">Manassés</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Naftali\">Naftali</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Rúben\">Rúben</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Simeão\">Simeão</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Zebulon\">Zebulon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"Zebulon 2\">Zebulon 2</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Batizado?</th>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"batizado\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option name=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SIM\">Sim</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"NÃO\">Não</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Email:</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"ex.: consolidar@apascentar.com.br\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Telefone:</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" name=\"telefone\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"ex.: 21 98765432\" maxlength=\"12\" required=\"required\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Já foi ao Retiro?</th>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"retiro\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"SIM\">Sim</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"NÃO\">Não</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
Calendar cal = Calendar.getInstance(); 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Quando foi ao Retiro?</th>\r\n");
      out.write("\t\t\t\t\t<td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<select name=\"quandoretiro\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Não foi\">Não Fui</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(178,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1990);
      // /index.jsp(178,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(cal.get(Calendar.YEAR));
      // /index.jsp(178,7) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      // /index.jsp(178,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Quando entrou na <br>Consolidação?\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"quantotempoconsolidacao\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /index.jsp(189,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1990);
      // /index.jsp(189,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(cal.get(Calendar.YEAR));
      // /index.jsp(189,7) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setStep(1);
      // /index.jsp(189,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Qual escola de <br>Servos? Faz?</th>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"servos\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"---\">--Selecione--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"NÃO FEZ\">Não Fiz</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Servos 2\">Servos 2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Servos 3\">Servos 3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Servos 4\">Servos 4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Servos 5\">Servos 5</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Raízes\">Raízes</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Foto</td><td><input type=\"file\" id=\"file\" accept=\".jpg, .jpeg, .png\" name=\"imagem\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><button type=\"submit\" class=\"badge badge-dark\">apagar</button></td>\r\n");
      out.write("\t\t\t\t\t<td><button type=\"submit\" class=\"badge badge-info\">enviar formulário</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
} else{
	request.setAttribute("login", "Login inválido!!");
	request.getRequestDispatcher("login.jsp").forward(request, response);
}


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
